// Auto-generated by `npx supabase gen types typescript`
// Run after each migration to regenerate.
// Placeholder until first migration in Sprint 1.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
