export type UserRole = "owner" | "admin" | "moderator" | "member"
export type MembershipStatus = "active" | "banned" | "pending"
export type PostType = "discussion" | "question" | "announcement"
export type CourseStatus = "draft" | "published" | "archived"
export type LessonType = "video" | "text" | "quiz"
export type EventStatus = "upcoming" | "live" | "ended" | "cancelled"
export type SubscriptionTier = "free" | "paid"
export type NotificationType =
  | "post_reply"
  | "comment_reply"
  | "mention"
  | "achievement"
  | "event_reminder"
  | "course_update"
